name: Run Python Script

on:
  schedule:
    # កូដនេះនឹងបញ្ជាឲ្យរត់រាល់ថ្ងៃនៅម៉ោង ៨:០០ ព្រឹក (ម៉ោងនៅកម្ពុជា)
    - cron: '0 1 * * *'
  workflow_dispatch: # ប៊ូតុងសម្រាប់ចុច Run តេស្តដោយដៃផ្ទាល់

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # បើកូដរបស់អ្នកមានប្រើប្រាស់ Library ក្រៅ (ដូចជា requests, selenium) ត្រូវសរសេរ pip install ថែមនៅទីនេះ

      - name: Execute Python Script
        run: python boostyt.py
